import fitz
import streamlit as st

uploaded_file = st.file_uploader(
  label = "Upload a financial report",
  type = ["pdf"],
  help = "Please only upload pdf files"
)
total = ""
if uploaded_file is not None:
  file_bytes = uploaded_file.read()
  finished_file = fitz.open(stream=file_bytes, filetype="pdf")
  for page_number in range(len(finished_file)):
    page = finished_file[page_number]
    text = page.get_text()
    lines = text.split('\n')
    for i, line in enumerate(lines):
      if line.lower() == ("cash generated by operating activities") or line.lower() == ("net cash provided by operating activities"):
        st.write(f"Found matching line: {line}")
        clean_line = lines[i+1].split()
        for word in clean_line:
          word = word.replace(",", "")
          st.write(f"Word:{word}")
          if word.isdigit():
             Debt_Equity_Ratio=word + ("\n")
             total = Debt_Equity_Ratio
             break;
          else:
             continue;
   
st.text_area("Extracted Text", total, height = 600, width = 1100)
  


 
