import pymupdf as fitz
import streamlit as st

uploaded_file = st.file_uploader(
  label = "Upload a financial report",
  type = ["pdf"],
  help = "Please only upload pdf files"
)
keywords = ["property", "plant", "equipment"]
replacements = {
    ",": "",
    "-": "",
    "/": "",
    "(": "",
    ")": ""
}
initial_num = 0
Free_Cash_Flow = 0
if uploaded_file is not None:
  file_bytes = uploaded_file.read()
  finished_file = fitz.open(stream=file_bytes, filetype="pdf")
  for page_number in range(len(finished_file)):
    page = finished_file[page_number]
    text = page.get_text()
    lines = text.split('\n')
  
    for index, line in enumerate(lines):
      if line.lower() == ("cash generated by operating activities") or line.lower() == ("net cash provided by operating activities"):
        nearby_lines = lines[index:index+5]
        for nearby_line in nearby_lines:
          for word in nearby_line.split():
              if(word.replace(",", "").isdigit()):
                clean_word = word.replace(",", "")
                total = int(clean_word)
                initial_num = total
                Free_Cash_Flow = total
                break;
              else:
                continue;
          if Free_Cash_Flow != 0:
             break;
    for index, line in enumerate(lines):
       if line.lower() == ("capital expenditures") or any(word in line.lower() for word in keywords):
          nearby_lines = lines[index:index+5]
          for nearby_line in nearby_lines:
            for word in nearby_line.split():
              if(word.translate(str.maketrans(replacements)).isdigit()):
                final_word = word.translate(str.maketrans(replacements))
                total = int(final_word)
                print(line"\n")
                print(total"\n")
                print(final_word"\n")
                Free_Cash_Flow -= total
                break;
              else:
                continue;
          if Free_Cash_Flow != 0 or Free_Cash_Flow != initial_num:
            break;
                  
                
                            
       if Free_Cash_Flow != 0 or Free_Cash_Flow != initial_num:
             break;

    if Free_Cash_Flow != 0 or Free_Cash_Flow != initial_num:
             break;
st.text_area("Extracted Text", Free_Cash_Flow, height = 600, width = 1100)
  


 
