import fitz
import streamlit as st

uploaded_file = st.file_uploader(
  label = "Upload a financial report",
  type = ["pdf"],
  help = "Please only upload pdf files"
)
Free_Cash_Flow = ""
if uploaded_file is not None:
  file_bytes = uploaded_file.read()
  finished_file = fitz.open(stream=file_bytes, filetype="pdf")
  for page_number in range(len(finished_file)):
    page = finished_file[page_number]
    text = page.get_text()
    lines = text.split('\n')
  
    for index, line in enumerate(lines):
      if line.lower() == ("cash generated by operating activities") or line.lower() == ("net cash provided by operating activities"):
        nearby_lines = lines[index:index+5]
        for nearby_line in nearby_lines:
          for word in nearby_line.split():
              if(word.replace(",", "").isdigit()):
                clean_word = word.replace(",", "")
                st.write(f"Word:{clean_word}")
                total = clean_word + ("\n")
                Free_Cash_Flow = total
                break;
              else:
                continue;
          if Free_Cash_Flow:
             break;
    for index, line in enumerate(lines):
       keywords = ["property", "plant", "equipment"]
       if line.lower() == ("Capital expenditures") or if all(word in line.lower() for word in keywords):
          nearby_lines = lines[index:index+5]
          for nearby_line in nearby_lines:
            for word in nearby_line.split():
              if(word.replace("("
                            
      if Free_Cash_Flow:
             break;

    if Free_Cash_Flow:
             break;
st.text_area("Extracted Text", total, height = 600, width = 1100)
  


 
